// p5.js, Three.js, WebGL API completion sources

const p5Completions = [
  // Lifecycle
  { label: 'setup', type: 'function', detail: 'p5.js lifecycle' },
  { label: 'draw', type: 'function', detail: 'p5.js lifecycle' },
  { label: 'preload', type: 'function', detail: 'p5.js lifecycle' },
  // Canvas
  { label: 'createCanvas', type: 'function', detail: '(w, h, [renderer])' },
  { label: 'resizeCanvas', type: 'function', detail: '(w, h)' },
  { label: 'background', type: 'function', detail: '(color)' },
  { label: 'pixelDensity', type: 'function', detail: '(density)' },
  // Shape
  { label: 'ellipse', type: 'function', detail: '(x, y, w, [h])' },
  { label: 'rect', type: 'function', detail: '(x, y, w, h)' },
  { label: 'line', type: 'function', detail: '(x1, y1, x2, y2)' },
  { label: 'triangle', type: 'function', detail: '(x1, y1, x2, y2, x3, y3)' },
  { label: 'quad', type: 'function', detail: '(x1, y1, x2, y2, x3, y3, x4, y4)' },
  { label: 'arc', type: 'function', detail: '(x, y, w, h, start, stop)' },
  { label: 'point', type: 'function', detail: '(x, y)' },
  { label: 'circle', type: 'function', detail: '(x, y, d)' },
  { label: 'square', type: 'function', detail: '(x, y, s)' },
  { label: 'beginShape', type: 'function', detail: '([kind])' },
  { label: 'endShape', type: 'function', detail: '([mode])' },
  { label: 'vertex', type: 'function', detail: '(x, y)' },
  { label: 'curveVertex', type: 'function', detail: '(x, y)' },
  { label: 'bezierVertex', type: 'function', detail: '(x2, y2, x3, y3, x4, y4)' },
  { label: 'bezier', type: 'function', detail: '(x1, y1, x2, y2, x3, y3, x4, y4)' },
  { label: 'curve', type: 'function', detail: '(x1, y1, x2, y2, x3, y3, x4, y4)' },
  // Color
  { label: 'fill', type: 'function', detail: '(color)' },
  { label: 'noFill', type: 'function', detail: '()' },
  { label: 'stroke', type: 'function', detail: '(color)' },
  { label: 'noStroke', type: 'function', detail: '()' },
  { label: 'strokeWeight', type: 'function', detail: '(weight)' },
  { label: 'colorMode', type: 'function', detail: '(mode, [max])' },
  { label: 'color', type: 'function', detail: '(r, g, b, [a])' },
  { label: 'lerpColor', type: 'function', detail: '(c1, c2, amt)' },
  // Transform
  { label: 'translate', type: 'function', detail: '(x, y, [z])' },
  { label: 'rotate', type: 'function', detail: '(angle)' },
  { label: 'scale', type: 'function', detail: '(s | x, y)' },
  { label: 'push', type: 'function', detail: '()' },
  { label: 'pop', type: 'function', detail: '()' },
  { label: 'rotateX', type: 'function', detail: '(angle)' },
  { label: 'rotateY', type: 'function', detail: '(angle)' },
  { label: 'rotateZ', type: 'function', detail: '(angle)' },
  // Math
  { label: 'map', type: 'function', detail: '(val, start1, stop1, start2, stop2)' },
  { label: 'constrain', type: 'function', detail: '(val, low, high)' },
  { label: 'lerp', type: 'function', detail: '(start, stop, amt)' },
  { label: 'norm', type: 'function', detail: '(val, start, stop)' },
  { label: 'dist', type: 'function', detail: '(x1, y1, x2, y2)' },
  { label: 'mag', type: 'function', detail: '(x, y)' },
  { label: 'noise', type: 'function', detail: '(x, [y], [z])' },
  { label: 'noiseSeed', type: 'function', detail: '(seed)' },
  { label: 'noiseDetail', type: 'function', detail: '(lod, falloff)' },
  { label: 'random', type: 'function', detail: '([min], [max])' },
  { label: 'randomSeed', type: 'function', detail: '(seed)' },
  { label: 'randomGaussian', type: 'function', detail: '([mean], [sd])' },
  { label: 'sin', type: 'function', detail: '(angle)' },
  { label: 'cos', type: 'function', detail: '(angle)' },
  { label: 'tan', type: 'function', detail: '(angle)' },
  { label: 'atan2', type: 'function', detail: '(y, x)' },
  { label: 'radians', type: 'function', detail: '(degrees)' },
  { label: 'degrees', type: 'function', detail: '(radians)' },
  { label: 'abs', type: 'function', detail: '(n)' },
  { label: 'floor', type: 'function', detail: '(n)' },
  { label: 'ceil', type: 'function', detail: '(n)' },
  { label: 'round', type: 'function', detail: '(n)' },
  { label: 'pow', type: 'function', detail: '(n, e)' },
  { label: 'sqrt', type: 'function', detail: '(n)' },
  { label: 'min', type: 'function', detail: '(a, b)' },
  { label: 'max', type: 'function', detail: '(a, b)' },
  // Vector
  { label: 'createVector', type: 'function', detail: '(x, y, [z])' },
  // Image
  { label: 'loadImage', type: 'function', detail: '(path)' },
  { label: 'image', type: 'function', detail: '(img, x, y, [w], [h])' },
  { label: 'tint', type: 'function', detail: '(color)' },
  { label: 'noTint', type: 'function', detail: '()' },
  { label: 'loadPixels', type: 'function', detail: '()' },
  { label: 'updatePixels', type: 'function', detail: '()' },
  { label: 'get', type: 'function', detail: '(x, y)' },
  { label: 'set', type: 'function', detail: '(x, y, color)' },
  // Text
  { label: 'text', type: 'function', detail: '(str, x, y)' },
  { label: 'textSize', type: 'function', detail: '(size)' },
  { label: 'textAlign', type: 'function', detail: '(h, [v])' },
  { label: 'textFont', type: 'function', detail: '(font)' },
  { label: 'textWidth', type: 'function', detail: '(str)' },
  // Input
  { label: 'mouseX', type: 'variable', detail: 'number' },
  { label: 'mouseY', type: 'variable', detail: 'number' },
  { label: 'pmouseX', type: 'variable', detail: 'number' },
  { label: 'pmouseY', type: 'variable', detail: 'number' },
  { label: 'mouseIsPressed', type: 'variable', detail: 'boolean' },
  { label: 'keyIsPressed', type: 'variable', detail: 'boolean' },
  { label: 'key', type: 'variable', detail: 'string' },
  { label: 'keyCode', type: 'variable', detail: 'number' },
  { label: 'mousePressed', type: 'function', detail: 'event handler' },
  { label: 'mouseReleased', type: 'function', detail: 'event handler' },
  { label: 'mouseMoved', type: 'function', detail: 'event handler' },
  { label: 'mouseDragged', type: 'function', detail: 'event handler' },
  { label: 'keyPressed', type: 'function', detail: 'event handler' },
  { label: 'keyReleased', type: 'function', detail: 'event handler' },
  // Environment
  { label: 'width', type: 'variable', detail: 'number' },
  { label: 'height', type: 'variable', detail: 'number' },
  { label: 'frameCount', type: 'variable', detail: 'number' },
  { label: 'frameRate', type: 'function', detail: '([fps])' },
  { label: 'millis', type: 'function', detail: '()' },
  { label: 'deltaTime', type: 'variable', detail: 'number' },
  { label: 'windowWidth', type: 'variable', detail: 'number' },
  { label: 'windowHeight', type: 'variable', detail: 'number' },
  // Constants
  { label: 'PI', type: 'constant', detail: '3.14159...' },
  { label: 'TWO_PI', type: 'constant', detail: '6.28318...' },
  { label: 'HALF_PI', type: 'constant', detail: '1.57079...' },
  { label: 'QUARTER_PI', type: 'constant', detail: '0.78539...' },
  { label: 'TAU', type: 'constant', detail: '6.28318...' },
  { label: 'WEBGL', type: 'constant', detail: 'renderer mode' },
  { label: 'P2D', type: 'constant', detail: 'renderer mode' },
  // 3D
  { label: 'box', type: 'function', detail: '([w], [h], [d])' },
  { label: 'sphere', type: 'function', detail: '([radius])' },
  { label: 'cylinder', type: 'function', detail: '([radius], [height])' },
  { label: 'cone', type: 'function', detail: '([radius], [height])' },
  { label: 'torus', type: 'function', detail: '([radius], [tubeRadius])' },
  { label: 'plane', type: 'function', detail: '([w], [h])' },
  { label: 'camera', type: 'function', detail: '(x, y, z, cx, cy, cz, ux, uy, uz)' },
  { label: 'perspective', type: 'function', detail: '([fovy], [aspect], [near], [far])' },
  { label: 'ortho', type: 'function', detail: '([left], [right], [bottom], [top])' },
  { label: 'ambientLight', type: 'function', detail: '(color)' },
  { label: 'directionalLight', type: 'function', detail: '(color, x, y, z)' },
  { label: 'pointLight', type: 'function', detail: '(color, x, y, z)' },
  { label: 'specularMaterial', type: 'function', detail: '(color)' },
  { label: 'ambientMaterial', type: 'function', detail: '(color)' },
  { label: 'normalMaterial', type: 'function', detail: '()' },
  { label: 'createShader', type: 'function', detail: '(vert, frag)' },
  { label: 'shader', type: 'function', detail: '(shaderObj)' },
  { label: 'resetShader', type: 'function', detail: '()' },
];

const threeCompletions = [
  // Core
  { label: 'THREE.Scene', type: 'class', detail: 'Scene container' },
  { label: 'THREE.PerspectiveCamera', type: 'class', detail: '(fov, aspect, near, far)' },
  { label: 'THREE.OrthographicCamera', type: 'class', detail: '(left, right, top, bottom, near, far)' },
  { label: 'THREE.WebGLRenderer', type: 'class', detail: '({ antialias, alpha, ... })' },
  // Geometry
  { label: 'THREE.BoxGeometry', type: 'class', detail: '(w, h, d)' },
  { label: 'THREE.SphereGeometry', type: 'class', detail: '(radius, wSeg, hSeg)' },
  { label: 'THREE.PlaneGeometry', type: 'class', detail: '(w, h)' },
  { label: 'THREE.CylinderGeometry', type: 'class', detail: '(rTop, rBottom, h)' },
  { label: 'THREE.TorusGeometry', type: 'class', detail: '(r, tube, rSeg, tSeg)' },
  { label: 'THREE.TorusKnotGeometry', type: 'class', detail: '(r, tube, tSeg, rSeg)' },
  { label: 'THREE.BufferGeometry', type: 'class', detail: 'custom geometry' },
  { label: 'THREE.BufferAttribute', type: 'class', detail: '(array, itemSize)' },
  { label: 'THREE.IcosahedronGeometry', type: 'class', detail: '(radius, detail)' },
  { label: 'THREE.CircleGeometry', type: 'class', detail: '(radius, segments)' },
  { label: 'THREE.RingGeometry', type: 'class', detail: '(inner, outer, segments)' },
  // Material
  { label: 'THREE.MeshBasicMaterial', type: 'class', detail: '({ color, ... })' },
  { label: 'THREE.MeshStandardMaterial', type: 'class', detail: '({ color, roughness, metalness })' },
  { label: 'THREE.MeshPhongMaterial', type: 'class', detail: '({ color, shininess })' },
  { label: 'THREE.MeshLambertMaterial', type: 'class', detail: '({ color })' },
  { label: 'THREE.MeshNormalMaterial', type: 'class', detail: '()' },
  { label: 'THREE.ShaderMaterial', type: 'class', detail: '({ uniforms, vertexShader, fragmentShader })' },
  { label: 'THREE.RawShaderMaterial', type: 'class', detail: '({ uniforms, vertexShader, fragmentShader })' },
  { label: 'THREE.LineBasicMaterial', type: 'class', detail: '({ color })' },
  { label: 'THREE.PointsMaterial', type: 'class', detail: '({ color, size })' },
  // Objects
  { label: 'THREE.Mesh', type: 'class', detail: '(geometry, material)' },
  { label: 'THREE.Group', type: 'class', detail: 'object container' },
  { label: 'THREE.Line', type: 'class', detail: '(geometry, material)' },
  { label: 'THREE.Points', type: 'class', detail: '(geometry, material)' },
  { label: 'THREE.InstancedMesh', type: 'class', detail: '(geometry, material, count)' },
  // Light
  { label: 'THREE.AmbientLight', type: 'class', detail: '(color, intensity)' },
  { label: 'THREE.DirectionalLight', type: 'class', detail: '(color, intensity)' },
  { label: 'THREE.PointLight', type: 'class', detail: '(color, intensity, distance)' },
  { label: 'THREE.SpotLight', type: 'class', detail: '(color, intensity)' },
  { label: 'THREE.HemisphereLight', type: 'class', detail: '(skyColor, groundColor, intensity)' },
  // Math
  { label: 'THREE.Vector2', type: 'class', detail: '(x, y)' },
  { label: 'THREE.Vector3', type: 'class', detail: '(x, y, z)' },
  { label: 'THREE.Vector4', type: 'class', detail: '(x, y, z, w)' },
  { label: 'THREE.Matrix4', type: 'class', detail: '4x4 matrix' },
  { label: 'THREE.Quaternion', type: 'class', detail: '(x, y, z, w)' },
  { label: 'THREE.Euler', type: 'class', detail: '(x, y, z, order)' },
  { label: 'THREE.Color', type: 'class', detail: '(r, g, b)' },
  { label: 'THREE.Clock', type: 'class', detail: '([autoStart])' },
  { label: 'THREE.MathUtils', type: 'namespace', detail: 'math utilities' },
  // Texture
  { label: 'THREE.TextureLoader', type: 'class', detail: '()' },
  { label: 'THREE.CubeTextureLoader', type: 'class', detail: '()' },
  // Controls & Loaders (common addons)
  { label: 'THREE.OrbitControls', type: 'class', detail: '(camera, domElement)' },
  // Raycaster
  { label: 'THREE.Raycaster', type: 'class', detail: '()' },
];

const webglCompletions = [
  // Context
  { label: 'getContext', type: 'function', detail: "('webgl') | ('webgl2')" },
  // Shaders
  { label: 'createShader', type: 'function', detail: '(type)' },
  { label: 'shaderSource', type: 'function', detail: '(shader, source)' },
  { label: 'compileShader', type: 'function', detail: '(shader)' },
  { label: 'getShaderParameter', type: 'function', detail: '(shader, pname)' },
  { label: 'getShaderInfoLog', type: 'function', detail: '(shader)' },
  { label: 'deleteShader', type: 'function', detail: '(shader)' },
  // Program
  { label: 'createProgram', type: 'function', detail: '()' },
  { label: 'attachShader', type: 'function', detail: '(program, shader)' },
  { label: 'linkProgram', type: 'function', detail: '(program)' },
  { label: 'useProgram', type: 'function', detail: '(program)' },
  { label: 'getProgramParameter', type: 'function', detail: '(program, pname)' },
  { label: 'getProgramInfoLog', type: 'function', detail: '(program)' },
  { label: 'deleteProgram', type: 'function', detail: '(program)' },
  // Attributes
  { label: 'getAttribLocation', type: 'function', detail: '(program, name)' },
  { label: 'enableVertexAttribArray', type: 'function', detail: '(index)' },
  { label: 'vertexAttribPointer', type: 'function', detail: '(index, size, type, normalized, stride, offset)' },
  // Uniforms
  { label: 'getUniformLocation', type: 'function', detail: '(program, name)' },
  { label: 'uniform1f', type: 'function', detail: '(location, v)' },
  { label: 'uniform2f', type: 'function', detail: '(location, x, y)' },
  { label: 'uniform3f', type: 'function', detail: '(location, x, y, z)' },
  { label: 'uniform4f', type: 'function', detail: '(location, x, y, z, w)' },
  { label: 'uniform1i', type: 'function', detail: '(location, v)' },
  { label: 'uniformMatrix4fv', type: 'function', detail: '(location, transpose, value)' },
  // Buffers
  { label: 'createBuffer', type: 'function', detail: '()' },
  { label: 'bindBuffer', type: 'function', detail: '(target, buffer)' },
  { label: 'bufferData', type: 'function', detail: '(target, data, usage)' },
  { label: 'deleteBuffer', type: 'function', detail: '(buffer)' },
  // Texture
  { label: 'createTexture', type: 'function', detail: '()' },
  { label: 'bindTexture', type: 'function', detail: '(target, texture)' },
  { label: 'texImage2D', type: 'function', detail: '(target, level, internalformat, ...)' },
  { label: 'texParameteri', type: 'function', detail: '(target, pname, param)' },
  { label: 'activeTexture', type: 'function', detail: '(texture)' },
  // Drawing
  { label: 'drawArrays', type: 'function', detail: '(mode, first, count)' },
  { label: 'drawElements', type: 'function', detail: '(mode, count, type, offset)' },
  { label: 'clear', type: 'function', detail: '(mask)' },
  { label: 'clearColor', type: 'function', detail: '(r, g, b, a)' },
  { label: 'viewport', type: 'function', detail: '(x, y, width, height)' },
  { label: 'enable', type: 'function', detail: '(cap)' },
  { label: 'disable', type: 'function', detail: '(cap)' },
  { label: 'blendFunc', type: 'function', detail: '(sfactor, dfactor)' },
  // Framebuffer
  { label: 'createFramebuffer', type: 'function', detail: '()' },
  { label: 'bindFramebuffer', type: 'function', detail: '(target, framebuffer)' },
  { label: 'framebufferTexture2D', type: 'function', detail: '(target, attachment, textarget, texture, level)' },
  // Constants
  { label: 'VERTEX_SHADER', type: 'constant', detail: 'gl constant' },
  { label: 'FRAGMENT_SHADER', type: 'constant', detail: 'gl constant' },
  { label: 'ARRAY_BUFFER', type: 'constant', detail: 'gl constant' },
  { label: 'ELEMENT_ARRAY_BUFFER', type: 'constant', detail: 'gl constant' },
  { label: 'STATIC_DRAW', type: 'constant', detail: 'gl constant' },
  { label: 'DYNAMIC_DRAW', type: 'constant', detail: 'gl constant' },
  { label: 'TRIANGLES', type: 'constant', detail: 'gl constant' },
  { label: 'TRIANGLE_STRIP', type: 'constant', detail: 'gl constant' },
  { label: 'TRIANGLE_FAN', type: 'constant', detail: 'gl constant' },
  { label: 'LINES', type: 'constant', detail: 'gl constant' },
  { label: 'LINE_STRIP', type: 'constant', detail: 'gl constant' },
  { label: 'POINTS', type: 'constant', detail: 'gl constant' },
  { label: 'FLOAT', type: 'constant', detail: 'gl constant' },
  { label: 'UNSIGNED_SHORT', type: 'constant', detail: 'gl constant' },
  { label: 'DEPTH_TEST', type: 'constant', detail: 'gl constant' },
  { label: 'BLEND', type: 'constant', detail: 'gl constant' },
  { label: 'COLOR_BUFFER_BIT', type: 'constant', detail: 'gl constant' },
  { label: 'DEPTH_BUFFER_BIT', type: 'constant', detail: 'gl constant' },
  { label: 'TEXTURE_2D', type: 'constant', detail: 'gl constant' },
  { label: 'TEXTURE0', type: 'constant', detail: 'gl constant' },
  { label: 'COMPILE_STATUS', type: 'constant', detail: 'gl constant' },
  { label: 'LINK_STATUS', type: 'constant', detail: 'gl constant' },
];

const COMPLETIONS_MAP = {
  p5: p5Completions,
  three: threeCompletions,
  webgl: webglCompletions,
};

export function getCompletionSource(codeType) {
  const completions = COMPLETIONS_MAP[codeType] || [];
  return (context) => {
    const word = context.matchBefore(/[\w.]+/);
    if (!word || (word.from === word.to && !context.explicit)) return null;
    const input = context.state.sliceDoc(word.from, word.to).toLowerCase();
    const filtered = completions.filter((c) => c.label.toLowerCase().startsWith(input));
    if (filtered.length === 0) return null;
    return {
      from: word.from,
      options: filtered,
      validFor: /^[\w.]*$/,
    };
  };
}
